filter:
  excluded_paths:
    - "tests/"
build:
    environment:
        php:
            version: 7.0.7
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=phpunit.xml'
                coverage:
                    file: 'phpunit.xml'
                    format: 'clover'